<?php
function getLang($code) {
    $all = [
        'en' => ['welcome'=>'Welcome to AgriConnect!','login'=>'Login','register'=>'Register','name'=>'Full Name','phone'=>'Phone Number','password'=>'Password','shop_name'=>'Shop Name','email'=>'Email','address'=>'Address','logout'=>'Logout','dashboard'=>'Dashboard','products'=>'Products','orders'=>'My Orders','cart'=>'Cart','fertilizers'=>'Fertilizers','pesticides'=>'Pesticides','seeds'=>'Seeds','add_product'=>'Add Product','place_order'=>'Place Order','accept'=>'Accept','reject'=>'Reject','add_to_cart'=>'Add to Cart','total'=>'Total','stock'=>'Add Stock','live_tracking'=>'Live Tracking','forgot_pass'=>'Forgot Password?','already_acc'=>'Already have an account?','no_acc'=>"Don't have an account?",'farmer_note'=>'Register & Login to access Farmer panel','shop_note'=>'Register & Login to access Shop panel','pending'=>'Pending','delivered'=>'Delivered','accepted'=>'Accepted','rejected'=>'Rejected','out_for_delivery'=>'Out for Delivery','back'=>'Back','save'=>'Save','price'=>'Price','quantity'=>'Quantity','new_orders'=>'New Orders','farmer_details'=>'Farmer Details','shop_details'=>'Shop Details','manage_stock'=>'Manage Stock','browse'=>'Browse Products','search_placeholder'=>'Search fertilizers, seeds, pesticides...'],
        'te' => ['welcome'=>'AgriConnectకి స్వాగతం!','login'=>'లాగిన్','register'=>'నమోదు చేయి','name'=>'పూర్తి పేరు','phone'=>'ఫోన్ నంబర్','password'=>'పాస్‌వర్డ్','shop_name'=>'దుకాణం పేరు','email'=>'ఇమెయిల్','address'=>'చిరునామా','logout'=>'లాగ్ అవుట్','dashboard'=>'డాష్‌బోర్డ్','products'=>'ఉత్పత్తులు','orders'=>'నా ఆర్డర్లు','cart'=>'కార్ట్','fertilizers'=>'ఎరువులు','pesticides'=>'పురుగుమందులు','seeds'=>'విత్తనాలు','add_product'=>'ఉత్పత్తి జోడించు','place_order'=>'ఆర్డర్ చేయి','accept'=>'అంగీకరించు','reject'=>'తిరస్కరించు','add_to_cart'=>'కార్ట్‌కి జోడించు','total'=>'మొత్తం','stock'=>'స్టాక్ జోడించు','live_tracking'=>'లైవ్ ట్రాకింగ్','forgot_pass'=>'పాస్‌వర్డ్ మర్చిపోయారా?','already_acc'=>'ఇప్పటికే ఖాతా ఉందా?','no_acc'=>'ఖాతా లేదా?','farmer_note'=>'రైతు పానెల్ కోసం నమోదు & లాగిన్ తప్పనిసరి','shop_note'=>'షాప్ పానెల్ కోసం నమోదు & లాగిన్ తప్పనిసరి','pending'=>'పెండింగ్','delivered'=>'డెలివరీ అయింది','accepted'=>'అంగీకరించబడింది','rejected'=>'తిరస్కరించబడింది','out_for_delivery'=>'డెలివరీలో ఉంది','back'=>'వెనక్కి','save'=>'సేవ్ చేయి','price'=>'ధర','quantity'=>'పరిమాణం','new_orders'=>'కొత్త ఆర్డర్లు','farmer_details'=>'రైతు వివరాలు','shop_details'=>'షాప్ వివరాలు','manage_stock'=>'స్టాక్ నిర్వహించు','browse'=>'ఉత్పత్తులు చూడు','search_placeholder'=>'ఎరువులు, విత్తనాలు వెతకండి...'],
        'hi' => ['welcome'=>'AgriConnect में स्वागत!','login'=>'लॉगिन','register'=>'पंजीकरण','name'=>'पूरा नाम','phone'=>'फोन नंबर','password'=>'पासवर्ड','shop_name'=>'दुकान का नाम','email'=>'ईमेल','address'=>'पता','logout'=>'लॉग आउट','dashboard'=>'डैशबोर्ड','products'=>'उत्पाद','orders'=>'मेरे ऑर्डर','cart'=>'कार्ट','fertilizers'=>'उर्वरक','pesticides'=>'कीटनाशक','seeds'=>'बीज','add_product'=>'उत्पाद जोड़ें','place_order'=>'ऑर्डर करें','accept'=>'स्वीकार','reject'=>'अस्वीकार','add_to_cart'=>'कार्ट में जोड़ें','total'=>'कुल','stock'=>'स्टॉक जोड़ें','live_tracking'=>'लाइव ट्रैकिंग','forgot_pass'=>'पासवर्ड भूल गए?','already_acc'=>'पहले से खाता है?','no_acc'=>'खाता नहीं है?','farmer_note'=>'किसान पैनल के लिए पंजीकरण करें','shop_note'=>'शॉप पैनल के लिए पंजीकरण करें','pending'=>'लंबित','delivered'=>'डिलीवर','accepted'=>'स्वीकृत','rejected'=>'अस्वीकृत','out_for_delivery'=>'डिलीवरी पर','back'=>'वापस','save'=>'सेव','price'=>'मूल्य','quantity'=>'मात्रा','new_orders'=>'नए ऑर्डर','farmer_details'=>'किसान विवरण','shop_details'=>'दुकान विवरण','manage_stock'=>'स्टॉक प्रबंधन','browse'=>'उत्पाद देखें','search_placeholder'=>'उर्वरक, बीज, कीटनाशक खोजें...'],
        'ta' => ['welcome'=>'AgriConnectக்கு வரவேற்கிறோம்!','login'=>'உள்நுழை','register'=>'பதிவு செய்','name'=>'முழு பெயர்','phone'=>'தொலைபேசி','password'=>'கடவுச்சொல்','shop_name'=>'கடை பெயர்','email'=>'மின்னஞ்சல்','address'=>'முகவரி','logout'=>'வெளியேறு','dashboard'=>'டாஷ்போர்டு','products'=>'தயாரிப்புகள்','orders'=>'என் ஆர்டர்கள்','cart'=>'கார்ட்','fertilizers'=>'உரங்கள்','pesticides'=>'பூச்சிக்கொல்லி','seeds'=>'விதைகள்','add_product'=>'பொருள் சேர்','place_order'=>'ஆர்டர் செய்','accept'=>'ஏற்கவும்','reject'=>'நிராகரி','add_to_cart'=>'கார்டில் சேர்','total'=>'மொத்தம்','stock'=>'கையிருப்பு சேர்','live_tracking'=>'நேரடி கண்காணிப்பு','forgot_pass'=>'கடவுச்சொல் மறந்தீர்களா?','already_acc'=>'ஏற்கனவே கணக்கு உள்ளதா?','no_acc'=>'கணக்கு இல்லையா?','farmer_note'=>'விவசாயி பேனலுக்கு பதிவு தேவை','shop_note'=>'கடை பேனலுக்கு பதிவு தேவை','pending'=>'நிலுவை','delivered'=>'டெலிவரி','accepted'=>'ஏற்கப்பட்டது','rejected'=>'நிராகரிக்கப்பட்டது','out_for_delivery'=>'டெலிவரியில்','back'=>'பின்செல்','save'=>'சேமி','price'=>'விலை','quantity'=>'அளவு','new_orders'=>'புதிய ஆர்டர்கள்','farmer_details'=>'விவசாயி விவரங்கள்','shop_details'=>'கடை விவரங்கள்','manage_stock'=>'கையிருப்பு நிர்வகி','browse'=>'பொருட்கள் பார்','search_placeholder'=>'உரம், விதை, பூச்சிக்கொல்லி தேடு...'],
    ];
    return $all[$code] ?? $all['en'];
}
?>
